"""add unique constraint user badge

Revision ID: 23032fb1c4fc
Revises: dcce0ebef10a
Create Date: 2026-07-28 14:47:08.201734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23032fb1c4fc'
down_revision: Union[str, Sequence[str], None] = 'dcce0ebef10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_badge', 'user_badges', ['user_id', 'badge_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_badge', 'user_badges', type_='unique')
    # ### end Alembic commands ###
